#!/usr/bin/env python3
"""Atlas case parts generator — CadQuery scripts driven by keyboard.yaml.

Generates:
  - Full assembly view (PCB + trackpoint sensor + companion board)
  - Trackpoint spacer
  - (future) bottom plate, keyplate, housing

Usage:
    python3 tools/case/case_build.py -l tools/keyboard.yaml
    python3 tools/case/case_build.py --part assembly
    python3 tools/case/case_build.py --part spacer
"""
import argparse
import os
import sys
from pathlib import Path

import cadquery as cq
import yaml

TOOLS_DIR = Path(__file__).resolve().parent.parent
MODELS_DIR = TOOLS_DIR / "3dmodels"
BUILD_DIR = TOOLS_DIR / "build"


# ---------------------------------------------------------------------------
# Trackpoint module (sensor + companion board)
# ---------------------------------------------------------------------------


def load_trackpoint_module(layout: dict) -> tuple[cq.Workplane, cq.Workplane]:
    """Load sensor STEP and build companion board from keyboard.yaml dimensions.

    Returns (sensor, companion_board) both centered on stick origin.
    """
    tp = layout["trackpoint"]

    # Load sensor and center on stick
    sensor_file = MODELS_DIR / tp["sensor_step"]
    sensor = cq.importers.importStep(str(sensor_file))
    stick_y = tp.get("stick_offset_y", 1.70)
    sensor = sensor.translate((0, -stick_y, 0))

    # Companion board from config
    cb = tp["companion_board"]
    companion = cq.Workplane("XY").box(cb["width"], cb["height"], cb["thickness"])

    return sensor, companion


def build_assembly(layout: dict) -> None:
    """Build full assembly: keyboard PCB + trackpoint modules.

    Uses the pre-built trackpoint_module.step (sensor + companion board)
    generated by tp_assembly.py.
    """
    pcb_step = BUILD_DIR / "export" / "keyboard.step"
    if not pcb_step.exists():
        print(f"Error: {pcb_step} not found. Run 'just pcb-export && just pcb-step' first.")
        sys.exit(1)

    tp_module_step = MODELS_DIR / "trackpoint_module.step"
    if not tp_module_step.exists():
        print(f"Error: {tp_module_step} not found. Run tp_assembly.py first.")
        sys.exit(1)

    pcb = cq.importers.importStep(str(pcb_step))
    tp_module = cq.importers.importStep(str(tp_module_step))
    tp_bb = tp_module.val().BoundingBox()

    tp_positions = _read_trackpoint_positions()

    # Module Z: bracket contact surface (Z=0.8 in module) touches PCB bottom (Z=-1.6 in STEP)
    # Bracket surface found by face analysis: largest flat face at Z=0.800
    bracket_surface_z = 1.1
    pcb_bottom_z = -1.6
    module_z = pcb_bottom_z - bracket_surface_z

    parts = [pcb.val()]

    for half, (tx, ty) in zip(["L", "R"], tp_positions):
        # Left: -90° (companion points inward), Right: 90°
        rot = -90 if half == "L" else 90
        m = tp_module.rotate((0, 0, 0), (0, 0, 1), rot)
        m = m.translate((tx, ty, module_z))
        parts.append(m.val())

    combined = cq.Compound.makeCompound(parts)
    out = BUILD_DIR / "case" / "assembly.step"
    out.parent.mkdir(parents=True, exist_ok=True)
    cq.exporters.export(cq.Workplane().add(combined), str(out))
    size = os.path.getsize(out) / 1e6
    print(f"  Assembly: {out} ({size:.1f} MB)")


def _read_trackpoint_positions() -> list[tuple[float, float]]:
    """Read trackpoint stick positions from the PCB file.

    Parses the .kicad_pcb text directly to avoid pcbnew dependency
    (pcbnew's PYTHONPATH conflicts with CadQuery's).
    """
    import re
    pcb_path = BUILD_DIR / "keyboard.kicad_pcb"
    if not pcb_path.exists():
        print("  Warning: PCB not found, using default positions")
        return [(92.59, -85.95), (204.32, -85.95)]

    text = pcb_path.read_text()
    positions = []
    # Find TP_*_stick footprints and extract their (at x y) coordinates
    for m in re.finditer(
        r'\(footprint\b[^)]*\n.*?reference\s+"(TP_\w+_stick)".*?\(at\s+([\d.]+)\s+([\d.]+)',
        text, re.DOTALL
    ):
        x, y = float(m.group(2)), float(m.group(3))
        positions.append((x, -y))  # STEP coords: negate Y

    positions.sort(key=lambda p: p[0])
    return positions if positions else [(92.59, -85.95), (204.32, -85.95)]


# ---------------------------------------------------------------------------
# Trackpoint spacer
# ---------------------------------------------------------------------------


def build_spacer(layout: dict) -> None:
    """Thin plate between PCB underside and trackpoint bracket.

    Covers protruding solder joints so the metal bracket sits flat.
    """
    tp = layout["trackpoint"]
    center_diam = tp["center_hole"]
    screw_diam = tp["screw_holes"]["diameter"]
    screw_offset = tp["screw_holes"]["offset"]

    thickness = 1.2
    width = 12.0
    height = screw_offset * 2 + 6.0

    spacer = (
        cq.Workplane("XY")
        .box(width, height, thickness)
        .faces(">Z").workplane().hole(center_diam)
        .faces(">Z").workplane()
        .pushPoints([(0, -screw_offset), (0, screw_offset)])
        .hole(screw_diam + 0.2)
    )

    out_dir = BUILD_DIR / "case"
    out_dir.mkdir(parents=True, exist_ok=True)

    for fmt, ext in [("STEP", ".step"), ("STL", ".stl")]:
        out = out_dir / f"trackpoint_spacer{ext}"
        cq.exporters.export(spacer, str(out))
        print(f"  Spacer: {out}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-l", "--layout", type=Path, default=TOOLS_DIR / "keyboard.yaml",
    )
    parser.add_argument(
        "--part", choices=["assembly", "spacer", "all"], default="all",
    )
    args = parser.parse_args()

    layout = yaml.safe_load(args.layout.read_text())

    if args.part in ("assembly", "all"):
        print("Building assembly...")
        build_assembly(layout)

    if args.part in ("spacer", "all"):
        print("Building spacer...")
        build_spacer(layout)


if __name__ == "__main__":
    main()
