# Right side is a peripheral
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Enable BLE
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE=y

# Enable NFC pins as GPIO (for trackpoint reset on P0.09)
CONFIG_NFCT_PINS_AS_GPIOS=y

# Enable pointing/mouse support for trackpoint
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_GPIO=y

# UART-based PS/2 driver config
CONFIG_UART_INTERRUPT_DRIVEN=y

# Battery reporting to central
CONFIG_ZMK_BATTERY_REPORTING=y
